### ISSUE TITLE
MatrixRate causing Issues with Component manager - Magento 2.1.3 

### ISSUE THREAD

**Issue by soylentrg** [webshopapps/module-matrixrate#17] opened 2017-01-02 19:26 UTC
I'm having problems with MatrixRate causing issues in Component Manager in Magento 2.1.3. I think It might have been happening on 2.1.2 but I have only just tied this issue down.
I have repeated this  several times on different servers and its exactly the same each time.

If I install MatrixRate module (as per webshopapps instructions) on a fresh install of Magento 2.1.3 I get the following issues:

First problem is that it causes Component Manager to get stuck in endless "please wait"
![matrix_rate_please_wait](https://cloud.githubusercontent.com/assets/24880418/21594997/de19f0f6-d120-11e6-8fc8-d2a991b8e150.JPG)

If I go back and remove the public/private keys in System Config I can get past the "please wait" and get into Component Manager. I'm then presented with a blank module that was not there before installing Matrix Rates.
![matrix_rate_blank_module](https://cloud.githubusercontent.com/assets/24880418/21595007/ee7b7df2-d120-11e6-8410-8db790386341.JPG)

Down at the bottom of the list of modules is Matrixrate, shown as not enabled.
![matrix_rate_disabled_module](https://cloud.githubusercontent.com/assets/24880418/21595011/f63d2d88-d120-11e6-98a3-323a06fda259.JPG)

Despite being shown as Disabled in component manager, the module is however enabled and seems to function OK. If I do command "php bin/magento module:status" via SSH it shows the MatrixRate module as enabled. 
![matrix_rate_is_enabled](https://cloud.githubusercontent.com/assets/24880418/21595013/fbd3b064-d120-11e6-86a5-957c72f58ae6.JPG)

Magento has been installed using Softaculous and also using PHP 7

Any ideas how to fix this?

**Comment by wsagen** [comment] 2017-01-03 01:52
On issue 1 with "please wait" can you confirm this ONLY occurs when MatrixRate is installed? 
I see others are experiencing this issue unrelated to our extension
https://github.com/magento/magento2/issues/7958

**Comment by soylentrg** [comment] 2017-01-03 02:57
Yes I can confirm this. The install does not have the "please wait" issue before I install matrixrate module.

**Comment by soylentrg** [comment] 2017-01-03 03:13
I can also install other modules without causing the "please wait" issue.

**Comment by soylentrg** [comment] 2017-01-04 10:36
Further to above issues, when I try entering my magento marketplace keys in System Config it throws up a MatrixRate related error. See screen shot:
![matrix_rate_marketplace_keys](https://cloud.githubusercontent.com/assets/24880418/21639771/adb95a7e-d269-11e6-8254-1649fd7d535f.JPG)

**Comment by soylentrg** [comment] 2017-01-05 09:52
Have just tried installing matrixrate on a VPS server and without using Softaculous and I still get the same problems. 

Is anyone looking at this?  We're considering using ShipperHQ but this is a show stopper.

**Comment by wsajosh** [comment] 2017-01-05 14:15
This is a known Magento issue. It looks like they've marked it as fixed, but not pushed the code into production yet. More info is here: https://github.com/magento/magento2/issues/6718

I can confirm this is the same issue as described in the bug report above. Error when I step through this in debugger is: Couldn't get available versions for package webshopapps/module-matrixrate

**Closed by wsajosh** 2017-01-05 14:15 UTC
