### ISSUE TITLE
Free shipping promo code 

### ISSUE THREAD

**Issue by dcruz11** [webshopapps/module-matrixrate#82] opened 2020-04-07 16:40 UTC
I was trying to create a promo code with free shipping and I saw it is not possible. 
I looked at https://github.com/webshopapps/module-matrixrate/issues/77#issuecomment-539424235 where answer that.
My question is: is possible to use discount percent promo code? how could I allow that free shipping promocode? is there any payment version of the module where it is allowed?

Thanks, I hope for your answer.

**Comment by ibraheemnabeelfauzi** [comment] 2020-04-08 15:51
Hey @dcruz11 percent promo codes aren't supported however you can use free shipping promotional code to discount the desired shipping method to zero using Premium Matrix Rate: https://webshopapps.com/us/premium-matrixrate-shipping-extension.html (this is the paid extension). 

Here is a doc on how to do so: http://support.webshopapps.com/premium/creating-free-shipping-promotions/

**Comment by dcruz11** [comment] 2020-04-13 15:32
Thanks Ibraheem,
I would like to know about the possibilities to use the same module or a payment version. Nevertheless, I would like also to know about the exact limitations  of the this free module...
Any other answer please?

**Comment by ibraheemnabeelfauzi** [comment] 2020-04-15 14:08
Hello @dcruz11 could you please provide us with your email address so we can send you all this detailed information. 

Thank you.

**Comment by dcruz11** [comment] 2020-04-16 07:57
Thanks Ibraheem, however firstly I would like to know the limitations of this current module and if there is any powerful version.

**Comment by dudzio12** [comment] 2020-04-16 14:12
@ibraheemnabeelfauzi - Is it intended or can I eventually make a PR that makes that possible? :)

**Comment by dudzio12** [comment] 2020-04-16 15:02
So after few minutes with debugging I found out that my quote has zero weight.
If we use package_weight condition with zero weight shipping rate request, we have an issue:
If condition method has `condition_from_value` equal 0 - we will never going to have condition `condition_from_value > 0` true.

We can although make `condition_from_value` field like -1, so it will work as expected.

We can easily fix this issue with simple if statement:
```
            if($bind[':condition_name'] === "package_weight" && $bind[':condition_value'] == 0) {
                $select->where('condition_from_value <= :condition_value');
            } else {
                $select->where('condition_from_value < :condition_value');
            }
```

I'm not sure if we should though, because it seems like Magento bug and I reported it actually here:
https://github.com/magento/magento2/issues/27875

@ibraheemnabeelfauzi Please inform me if you want me to implement above statement or not.

Hope that helps you a bit @dcruz11.

**Comment by dudzio12** [comment] 2020-04-16 15:10
Unfortunately it might be that way by design...

https://magento.stackexchange.com/questions/3338/what-does-the-quotes-address-freemethodweight-represent

**Comment by dcruz11** [comment] 2020-04-17 10:41
Thanks @dudzio12 
then? what could we do to use a promo free shipping code with this module-matrixrate?

**Comment by dudzio12** [comment] 2020-04-17 10:45
@dcruz11 So we have two options as I explained:
1) Modify matrixrate extension to work with weight changing to zero when free shipping rule is applied to the quote.
2) Always use -1 as `condition_from_value` when `condition_name` is `package_weight`  (exactly as on the screenshot above).

**Comment by dudzio12** [comment] 2020-04-17 10:48
Actually there is a third option - that Magento Team will mark this as actual bug and fix the issue. To be honest - I don't think this will happen and if it does - it won't be fixed in reasonable time though.

**Comment by dcruz11** [comment] 2020-04-24 12:34
Thanks @dudzio12 . Your words are really helpful.

**Closed** 2020-12-21 11:34 UTC

**Comment by barbazul** [comment] 2023-03-21 15:44
In case you got here looking for a fix: https://github.com/webshopapps/module-matrixrate/pull/119
